### ISSUE TITLE
Разобраться с подвязкой R-функционала в Python

### ISSUE THREAD

**Issue by EvilCommunist** [EvilCommunist/MathStat_GUI#6]
- [ ] Как использовать функции R для расчёта характеристик
- [ ] Как строить через Python R-графики
- [ ] Сравнить результат работы функционала с тестами на чистом R
